### ISSUE TITLE
There is no MSRVTT_JSFUSION_test.csv file

### ISSUE THREAD

**Issue by zhou-pig** [knightyxp/DGL#1]
FileNotFoundError: [Errno 2] No such file or directory: '/home/.../DGL/data/MSRVTT/MSRVTT_JSFUSION_test.csv'

scripts/msrvtt.sh: line 90: syntax error near unexpected token `done'
scripts/msrvtt.sh: line 90: `done'

**Comment by knightyxp** [comment]
Hi, sry for the late reply. I just updated the CSV file, you can also refer to the  https://github.com/jpthu17/DiffusionRet?tab=readme-ov-file, which provides the processed video at Google Cloud or Baiduyun, see  https://drive.google.com/drive/folders/1LYVUCPRxpKMRjCSfB_Gz-ugQa88FqDu_?usp=sharing.
