### ISSUE TITLE
What method did you use to visualize the attention in Fig.1(a) and Fig.5?

### ISSUE THREAD

**Issue by jianghaojun** [knightyxp/DGL#3]

**Comment by knightyxp** [comment]
In CLIP4Clip visualization, we extract the [CLS] token weights to frame patches for each frame. In DGL, the global prompts are attended to all patches in all frames, allowing us to display the dynamic attention weight across all frame tokens. The visualization code is currently in another branch. I will integrate it into the main branch soon if you need it.

**Comment by jianghaojun** [comment]
It would be of great help to me if you could provide the code, thanks a lot!

**Comment by knightyxp** [comment]
Hi haojun,
I am currently too busy with a new project. Can you give me your email so I can send you the zip of the visualization branch code? I will merge the visualization code to the main branch when I am free.

**Comment by jianghaojun** [comment]
Thanks a lot! 

Here is my email jianghaojunthu@163.com.

**Comment by knightyxp** [comment]
Send it. I will close this issue~

**Comment by zef1611** [comment]
Hi can I also ask for the visualization code @jianghaojun @knightyxp,  this would be a great help for my ongoing work. Here is my email: lehuy2316@gmail.com.  Thank you a lot and hope you have a nice day, cheers :D
