### ISSUE TITLE
About the method used to visualize the attention map

### ISSUE THREAD

**Issue by zef1611** [knightyxp/DGL#4]
Hi, This work is very nice and I am appreciated that you released the code repo. However, I have seen that you haven't released the visualization code for the attention map. So, can I ask for the release of the attention map visualization?

Thank you again for this wonderful work.

**Comment by knightyxp** [comment]
Hi,

Sorry for the late reply, I was really busy with the preparation of my ICLR submission. I have just updated the visualization code for the attention map, and you can access it here: https://drive.google.com/file/d/1tZudbN1_LdIzIg_2jrMGQR6lkQ3_-8se/view?usp=sharing.

Thank you again for your kind words and for your interest in my work!

Best regards,

**Comment by zef1611** [comment]
Thank you so much for taking the time to share your code with me. I truly appreciate your generosity, and I’m confident it will be incredibly helpful for my current research.

 I'm also wishing you the best of luck with your work—I hope it will be accepted just like your AAAI submission! It's been a pleasure to connect with you, and I look forward to staying in touch.
 
 Best,
 Huy
